// Code generated by goyacc -v parser/y.output -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

import (
	"fmt"
	"github.com/dogatana/yas80/errcode"
	"github.com/dogatana/yas80/filecontent"
	"github.com/dogatana/yas80/intern"
	"strings"
)

// goyacc が __yyfmt__ を勝手に import することの対策
var _ = __yyfmt__.Sprintf

//line parser/parser.y:15
type yySymType struct {
	yys           int
	token         Token
	num           Node
	statement     Statement
	err           any
	ident         *Ident
	enum_element  *EnumElement
	enum_elements *EnumElements
	block         *BlockStatement
	params        []string
	expr_list     *ExpressionList
	expr          Expression
}

const EOL = 57346
const FILE = 57347
const INCLUDE = 57348
const CHARMAP = 57349
const NUMBER = 57350
const STRING = 57351
const IDENT = 57352
const AT_IDENT = 57353
const LOCAL_IDENT = 57354
const ANON_IDENT = 57355
const DOT_IDENT = 57356
const Z80_INST0 = 57357
const Z80_INST1 = 57358
const Z80_INST2 = 57359
const Z80_REG8 = 57360
const Z80_REG16 = 57361
const Z80_FLAG = 57362
const ADDSUB = 57363
const MULDIV = 57364
const COMP = 57365
const SHIFT = 57366
const UNARY = 57367
const SL = 57368
const SR = 57369
const EQ = 57370
const NEQ = 57371
const GE = 57372
const LE = 57373
const OR = 57374
const AND = 57375
const CONCAT = 57376
const ORG = 57377
const CONST = 57378
const EQU = 57379
const VAR = 57380
const FUNCTION = 57381
const DATA = 57382
const DB = 57383
const DEFB = 57384
const DW = 57385
const DEFW = 57386
const DS = 57387
const DSB = 57388
const DSW = 57389
const DD = 57390
const IF = 57391
const ELSE = 57392
const ELIF = 57393
const ENDIF = 57394
const MACRO = 57395
const ENDM = 57396
const EXITM = 57397
const REPT = 57398
const ENDR = 57399
const FUNC = 57400
const ENDF = 57401
const RETURN = 57402
const PROC = 57403
const ENDP = 57404
const ENUM = 57405
const ENDE = 57406
const END = 57407
const INVALID = 57408

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EOL",
	"FILE",
	"INCLUDE",
	"CHARMAP",
	"NUMBER",
	"STRING",
	"IDENT",
	"AT_IDENT",
	"LOCAL_IDENT",
	"ANON_IDENT",
	"DOT_IDENT",
	"Z80_INST0",
	"Z80_INST1",
	"Z80_INST2",
	"Z80_REG8",
	"Z80_REG16",
	"Z80_FLAG",
	"ADDSUB",
	"MULDIV",
	"COMP",
	"SHIFT",
	"UNARY",
	"SL",
	"SR",
	"EQ",
	"NEQ",
	"GE",
	"LE",
	"OR",
	"AND",
	"CONCAT",
	"ORG",
	"CONST",
	"EQU",
	"VAR",
	"FUNCTION",
	"DATA",
	"DB",
	"DEFB",
	"DW",
	"DEFW",
	"DS",
	"DSB",
	"DSW",
	"DD",
	"IF",
	"ELSE",
	"ELIF",
	"ENDIF",
	"MACRO",
	"ENDM",
	"EXITM",
	"REPT",
	"ENDR",
	"FUNC",
	"ENDF",
	"RETURN",
	"PROC",
	"ENDP",
	"ENUM",
	"ENDE",
	"END",
	"'('",
	"')'",
	"','",
	"'<'",
	"'>'",
	"'~'",
	"'!'",
	"'^'",
	"'|'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'&'",
	"':'",
	"'['",
	"']'",
	"'='",
	"'%'",
	"INVALID",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:707

var includeDirs []string

func Parse(l *Lexer, dirs []string) *BlockStatement {
	// 常に有効
	yyErrorVerbose = true

	// loadIncludeFile で参照
	includeDirs = dirs

	// error トークンでリカバリすると yyParse() は 0 を返すため、戻り値には意味がない
	yyParse(l)
	return l.program
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 21,
	4, 72,
	68, 72,
	-2, 44,
	-1, 148,
	4, 70,
	68, 70,
	-2, 87,
	-1, 154,
	50, 53,
	51, 53,
	52, 53,
	-2, 0,
	-1, 193,
	50, 54,
	51, 54,
	52, 54,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 959

var yyAct = [...]uint8{
	16, 128, 105, 178, 114, 113, 140, 76, 46, 53,
	62, 42, 127, 64, 64, 56, 43, 10, 77, 78,
	144, 80, 83, 81, 65, 133, 86, 70, 71, 72,
	73, 68, 47, 70, 71, 79, 73, 112, 83, 90,
	91, 92, 93, 94, 95, 146, 54, 100, 5, 85,
	71, 45, 73, 174, 143, 127, 70, 71, 72, 73,
	142, 66, 108, 107, 111, 157, 127, 74, 75, 134,
	115, 116, 117, 118, 119, 120, 121, 123, 70, 71,
	72, 73, 147, 129, 143, 130, 131, 76, 126, 74,
	75, 145, 103, 76, 84, 70, 71, 72, 73, 138,
	83, 139, 61, 169, 83, 106, 74, 75, 88, 76,
	89, 61, 87, 64, 150, 151, 76, 177, 69, 137,
	165, 24, 104, 149, 143, 192, 167, 49, 156, 155,
	60, 153, 154, 101, 159, 59, 57, 160, 76, 152,
	58, 181, 70, 71, 72, 73, 96, 171, 158, 168,
	6, 170, 99, 74, 75, 76, 10, 11, 12, 13,
	51, 31, 44, 55, 29, 28, 30, 36, 176, 10,
	10, 33, 34, 35, 40, 185, 186, 50, 41, 188,
	164, 183, 184, 182, 10, 190, 10, 5, 23, 163,
	189, 2, 10, 161, 48, 1, 97, 32, 98, 193,
	5, 5, 76, 38, 141, 10, 166, 173, 7, 10,
	70, 71, 72, 73, 0, 5, 0, 5, 0, 39,
	0, 74, 75, 5, 0, 70, 71, 72, 73, 67,
	29, 28, 30, 0, 37, 122, 5, 75, 0, 9,
	5, 3, 4, 26, 27, 31, 44, 21, 29, 28,
	30, 36, 11, 12, 13, 33, 34, 35, 40, 0,
	0, 0, 41, 0, 0, 0, 0, 0, 0, 0,
	76, 0, 25, 14, 0, 15, 19, 42, 0, 0,
	0, 0, 43, 0, 0, 76, 18, 0, 0, 191,
	0, 0, 22, 17, 0, 0, 0, 20, 70, 71,
	72, 73, 8, 39, 0, 0, 0, 0, 0, 74,
	75, 0, 0, 0, 0, 0, 0, 9, 37, 3,
	4, 26, 27, 31, 44, 21, 29, 28, 30, 36,
	11, 12, 13, 33, 34, 35, 40, 0, 0, 0,
	41, 0, 0, 0, 0, 175, 0, 0, 0, 0,
	25, 14, 0, 15, 19, 42, 0, 0, 76, 0,
	43, 0, 0, 0, 18, 0, 0, 0, 0, 0,
	22, 17, 187, 0, 0, 20, 70, 71, 72, 73,
	8, 39, 0, 0, 0, 0, 0, 74, 75, 0,
	0, 0, 0, 0, 0, 9, 37, 3, 4, 26,
	27, 31, 44, 21, 29, 28, 30, 36, 11, 12,
	13, 33, 34, 35, 40, 0, 0, 0, 41, 0,
	0, 0, 135, 0, 0, 0, 0, 0, 25, 14,
	0, 15, 19, 42, 0, 0, 76, 0, 43, 0,
	0, 0, 18, 0, 0, 0, 0, 180, 22, 17,
	0, 0, 0, 20, 70, 71, 72, 73, 8, 39,
	0, 0, 0, 0, 0, 74, 75, 0, 0, 0,
	0, 0, 0, 9, 37, 3, 4, 26, 27, 31,
	44, 21, 29, 28, 30, 36, 11, 12, 13, 33,
	34, 35, 40, 0, 0, 0, 41, 0, 0, 0,
	148, 0, 0, 0, 0, 0, 25, 14, 0, 15,
	19, 42, 0, 0, 76, 0, 43, 0, 0, 0,
	18, 0, 0, 0, 0, 0, 22, 17, 0, 0,
	179, 20, 70, 71, 72, 73, 8, 39, 0, 0,
	0, 0, 0, 74, 75, 0, 0, 0, 0, 0,
	0, 9, 37, 3, 4, 26, 27, 31, 44, 21,
	29, 28, 30, 36, 11, 12, 13, 33, 34, 35,
	40, 0, 0, 0, 41, 0, 0, 0, 0, 136,
	0, 0, 0, 0, 25, 14, 0, 15, 19, 42,
	0, 0, 76, 0, 43, 0, 0, 0, 18, 0,
	0, 0, 0, 0, 22, 17, 172, 0, 0, 20,
	70, 71, 72, 73, 8, 39, 0, 0, 0, 0,
	0, 74, 75, 0, 0, 0, 0, 0, 0, 9,
	37, 3, 4, 26, 27, 31, 44, 21, 29, 28,
	30, 36, 11, 12, 13, 33, 34, 35, 40, 0,
	0, 0, 41, 0, 0, 0, 0, 132, 0, 0,
	0, 0, 25, 14, 0, 15, 19, 42, 0, 0,
	76, 0, 43, 0, 0, 0, 18, 0, 0, 0,
	0, 0, 22, 17, 0, 0, 0, 20, 0, 162,
	0, 0, 8, 39, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 9, 37, 3,
	4, 26, 27, 31, 44, 21, 29, 28, 30, 36,
	11, 12, 13, 33, 34, 35, 40, 0, 0, 125,
	41, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	25, 14, 0, 15, 19, 42, 70, 71, 72, 73,
	43, 0, 0, 0, 18, 0, 0, 74, 75, 0,
	22, 17, 0, 0, 0, 20, 0, 0, 52, 0,
	8, 39, 31, 44, 55, 29, 28, 30, 36, 0,
	0, 0, 33, 34, 35, 40, 37, 0, 0, 41,
	31, 44, 55, 29, 28, 30, 36, 0, 0, 0,
	33, 34, 35, 40, 0, 0, 76, 41, 31, 44,
	55, 29, 28, 30, 36, 124, 0, 0, 33, 34,
	35, 40, 102, 0, 0, 41, 0, 0, 0, 0,
	39, 0, 70, 71, 72, 73, 0, 0, 0, 70,
	71, 72, 73, 74, 75, 37, 0, 0, 39, 0,
	74, 75, 0, 70, 71, 72, 73, 0, 0, 0,
	0, 0, 0, 37, 74, 75, 63, 31, 44, 55,
	29, 28, 30, 36, 0, 0, 0, 110, 109, 35,
	40, 37, 0, 0, 41, 31, 44, 55, 29, 28,
	30, 36, 76, 0, 0, 33, 34, 35, 40, 76,
	0, 0, 41, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 76, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 39, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	37, 0, 0, 82, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 37,
}

var yyPact = [...]int16{
	-1000, 705, -1000, -1000, -1000, -29, 173, 156, 764, 132,
	77, -1000, 800, 800, 219, 219, 35, 782, 782, 219,
	782, 877, 45, -19, -1000, 782, 103, 98, -1000, -1000,
	-1000, -1000, 101, -1000, -1000, -1000, -1000, 782, -1000, 782,
	782, 782, 782, 782, -1000, 142, 782, 129, -19, -1000,
	-1000, -1000, -1000, 818, -1000, 26, 68, -1000, 118, 95,
	95, 782, -1000, 859, 832, -31, -78, -1000, -79, 782,
	782, 782, 782, 782, 782, 782, 153, 811, 725, 22,
	832, -56, 782, 832, 782, 782, 589, -1000, -43, -1000,
	-13, 355, -74, -74, 832, 511, -1000, 115, 782, 782,
	832, -1000, -1000, 782, -1000, 56, -1000, 16, 832, 24,
	15, 433, 800, 782, 782, 832, 28, -74, 12, -74,
	204, 6, -1000, 57, -1000, -1000, 95, 782, -2, 355,
	832, 832, 219, 782, -1000, -1000, 782, -1000, 189, -56,
	627, 116, -1000, 93, -1000, -1000, 782, -1000, -1000, -1000,
	832, 832, -1000, 549, 705, -14, 832, -1000, -1000, 277,
	832, -1000, -1000, -1000, -1000, -1000, 113, -80, 471, -1000,
	393, 74, -1000, 131, 782, 782, 315, -1000, 782, -1000,
	-1000, -1000, -1000, -1000, 782, 832, 832, -1000, 832, 237,
	121, -1000, -1000, 705,
}

var yyPgo = [...]uint8{
	0, 189, 150, 208, 207, 206, 188, 121, 6, 204,
	2, 1, 0, 203, 46, 10, 15, 197, 195,
}

var yyR1 = [...]int8{
	0, 18, 18, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	6, 6, 7, 7, 16, 16, 16, 16, 14, 14,
	10, 10, 10, 4, 4, 8, 8, 9, 9, 9,
	5, 5, 2, 2, 2, 2, 2, 15, 15, 15,
	15, 15, 11, 11, 11, 17, 17, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 13, 13,
}

var yyR2 = [...]int8{
	0, 0, 2, 1, 1, 3, 4, 2, 2, 2,
	3, 2, 4, 3, 5, 5, 4, 3, 5, 7,
	6, 8, 6, 6, 1, 2, 6, 2, 4, 1,
	3, 1, 2, 1, 2, 2, 4, 2, 4, 6,
	2, 3, 2, 4, 1, 1, 1, 1, 1, 3,
	0, 1, 3, 0, 5, 0, 2, 0, 2, 3,
	1, 3, 1, 1, 2, 2, 4, 3, 5, 3,
	3, 1, 0, 1, 3, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 4, 3, 1, 3, 3, 3,
	3, 3, 3, 3, 2, 2, 3, 4,
}

var yyChk = [...]int16{
	-1000, -18, -1, 4, 5, -14, -2, -3, 65, 2,
	-16, 15, 16, 17, 36, 38, -12, 56, 49, 39,
	60, 10, 55, -6, -7, 35, 6, 7, 12, 11,
	13, 8, -17, 18, 19, 20, 14, 81, -13, 66,
	21, 25, 40, 45, 9, 80, 37, 61, -6, -7,
	4, 4, 4, -12, -14, 10, -16, 4, 63, 58,
	53, 34, -15, 66, -12, -15, -14, 10, -16, 83,
	21, 22, 23, 24, 32, 33, 81, -12, -12, -16,
	-12, -11, 66, -12, 49, 68, -12, 9, 10, 9,
	-11, -12, -12, -12, -12, -12, 4, -2, 56, 10,
	-12, 4, 4, 66, 4, -10, 10, -10, -12, 19,
	18, -12, 68, 83, 83, -12, -12, -12, -12, -12,
	-12, -12, 82, -12, 4, 4, 66, 68, -11, -12,
	-12, -12, 68, 68, 82, 67, 68, 4, -12, -11,
	-8, -9, 4, 68, 4, 67, 21, 67, 67, -15,
	-12, -12, 82, -8, -8, -10, -12, 67, -16, -12,
	-12, 4, 62, -1, 64, 4, -5, 10, -8, 10,
	-8, -12, 57, -4, 67, 68, -8, 4, 83, 59,
	54, 67, 52, 50, 51, -12, -12, 57, -12, -8,
	-12, 52, 4, -8,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 4, 82, 0, 0, 0, 0,
	48, 62, 63, 0, 0, 0, 0, 0, 0, 0,
	24, -2, 29, 31, 33, 0, 0, 0, 45, 46,
	47, 77, 78, 79, 80, 81, 83, 72, 86, 0,
	0, 0, 0, 0, 75, 0, 0, 0, 32, 34,
	7, 8, 9, 0, 82, 44, 48, 11, 0, 50,
	50, 0, 64, 0, 71, 65, 0, 44, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	25, 27, 72, 73, 0, 0, 35, 37, 0, 76,
	0, 0, 94, 95, 40, 42, 5, 0, 0, 72,
	13, 55, 10, 72, 57, 0, 51, 0, 49, 80,
	79, 0, 0, 0, 0, 17, 88, 89, 90, 91,
	92, 93, 96, 0, 55, 55, 50, 0, 0, 73,
	30, 41, 0, 0, 85, 87, 0, 6, 0, 28,
	0, 0, 55, 0, 55, 67, 0, 69, -2, 66,
	12, 16, 97, 0, -2, 0, 74, 84, 36, 38,
	43, 55, 14, 56, 15, 58, 0, 60, 0, 52,
	0, 0, 18, 0, 0, 0, 0, 59, 0, 22,
	26, 68, 20, 55, 0, 23, 39, 19, 61, 0,
	0, 21, 55, -2,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 72, 3, 3, 3, 84, 79, 3,
	66, 67, 77, 75, 68, 76, 3, 78, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 80, 3,
	69, 83, 70, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 81, 3, 82, 73, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 74, 3, 71,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 85,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string, ctx *filecontent.Context) // # changed
	Push(filename string, fc *filecontent.FileContent, ctx *filecontent.Context) error // # added
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int, token Token) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return __yyfmt__.Sprintf("syntax error(state %d)", state)
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return __yyfmt__.Sprintf("syntax error(state %d): %s [token: %s]", state, e.msg, token.Literal)
		}
	}

	res := __yyfmt__.Sprintf("syntax error(state %d): unexpected '%s'", state, token.Literal)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			// if len(expected) == cap(expected) {
			//	return res
			// }
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("# lex %s(%d) %s\n", yyTokname(token), uint(char), lval.token.String()) // # changed
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn, yySave int // # changed
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
if yyDebug >= 2 {
	__yyfmt__.Println("# $end accept")
}
	return 0

ret1:
if yyDebug >= 2 {
	__yyfmt__.Println("# abort")
}
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	yySave = yystate // # added
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		if yyDebug >= 2 {
			__yyfmt__.Printf("# %d: shift %d\n", yySave, yystate) // # added
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken, yyrcvr.lval.token), yyrcvr.lval.token.Context)
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		rule, ok := grammerRules[yyn]
		if !ok {
			rule = ""
		}
		__yyfmt__.Printf("# %d: reduce (%d) %s\n", yystate, yyn, rule) // # changed
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]
	if yyDebug >= 2 {
		__yyfmt__.Printf("# top %d\n", yyS[yyp].yys) // # added
	}
	yySave = yyS[yyp].yys  // # added
	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	if yyDebug >= 2 {
		__yyfmt__.Printf("# %d: goto %d\n", yySave, yystate) // # added

	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:89
		{
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:91
		{
			if yyDollar[2].statement == nil {
				// do nothing
			} else if yyDollar[2].statement.NodeType() == NODE_ERROR {
				yylex.Error(yyDollar[2].statement.(*ParseError).Message, yyDollar[2].statement.(*ParseError).Context)
			} else {
				prog := yylex.(*Lexer).program
				prog.Block = append(prog.Block, yyDollar[2].statement)
				// END なら構文解析を終了する
				if yyDollar[2].statement.NodeType() == NODE_END_STMT {
					return 0
					// YYACCEPT
				}
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:108
		{
			yyVAL.statement = nil
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:109
		{
			yyVAL.statement = &FileStatement{Filename: yyDollar[1].token.Literal, Line: int(yyDollar[1].token.TokenSubType)}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:111
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[1].expr.(*ParseError)
			} else {
				yyVAL.statement = &LabelStatement{Name: yyDollar[1].expr, Context: yyDollar[2].token.Context}
			}
		}
	case 6:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:119
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[1].expr.(*ParseError)
			} else {
				yyDollar[3].statement.(*Z80Instruction).Label = yyDollar[1].expr
				yyVAL.statement = yyDollar[3].statement
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:127
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:128
		{
			if inc, ok := yyDollar[1].statement.(*IncludeStatement); ok {
				fc, err := loadIncludeFile(inc.Context.FileContent.Filename, inc.Filename)
				if err != nil {
					yyVAL.statement = &ParseError{Message: fmt.Sprintf(errcode.EFILE_NOT_FOUND, inc.Filename), Context: inc.Context}
				} else if err := yylex.Push(inc.Filename, fc, inc.Context); err != nil {
					yyVAL.statement = &ParseError{Message: err.Error(), Context: inc.Context}
				} else {
					yyVAL.statement = yyDollar[1].statement
				}
			} else {
				yyVAL.statement = yyDollar[1].statement
			}
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:142
		{
			yyVAL.statement = &EndStatement{Start: nil, Context: yyDollar[1].token.Context}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:145
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				yyVAL.statement = &EndStatement{Start: yyDollar[2].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:153
		{
			// ここで対処する前に syntax error が出力されているので改めてエラー出力はしない
			// lx.Error(__yyfmt__.Sprintf("[statement error] %s), $2.$1.String()), Context)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:160
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else if yyDollar[4].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else {
				yyVAL.statement = &ConstStatement{Name: yyDollar[2].expr, Value: yyDollar[4].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:170
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[1].expr.(*ParseError)
			} else if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else {
				yyVAL.statement = &ConstStatement{Name: yyDollar[1].expr, Value: yyDollar[3].expr, Context: yyDollar[2].token.Context}
			}
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:180
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[1].expr.(*ParseError)
			} else {
				yyVAL.statement = &ProcStatement{Name: yyDollar[1].expr, Block: yyDollar[4].block, Context: yyDollar[2].token.Context}
			}
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:188
		{
			yyVAL.statement = &EnumStatement{NameID: yyDollar[1].ident.NameID, Elements: yyDollar[4].enum_elements, Context: yyDollar[2].token.Context}
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:192
		{
			if yyDollar[4].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else {
				yyVAL.statement = &VariableStatement{Name: &Ident{Name: yyDollar[2].ident.Name, NameID: yyDollar[2].ident.NameID}, Value: yyDollar[4].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:200
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR && yyDollar[3].expr.NodeType() == NODE_ERROR {
				// 左辺のエラーを出力し、右辺のエラーを返す
				err := yyDollar[1].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
				yyVAL.statement = yyDollar[3].expr.(*ParseError)

			} else if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[1].expr.(*ParseError)
			} else if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else {
				yyVAL.statement = &AssignStatement{Left: yyDollar[1].expr, Value: yyDollar[3].expr, Context: yyDollar[2].token.Context}
			}
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:216
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				yyVAL.statement = &ReptStatement{MaxCount: yyDollar[2].expr, Block: yyDollar[4].block, Start: yyDollar[1].token.Context.Line, Context: yyDollar[5].token.Context}
			}
		}
	case 19:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:224
		{
			if yyDollar[4].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else {
				yyVAL.statement = &ReptStatement{Label: yyDollar[1].expr, MaxCount: yyDollar[4].expr, Block: yyDollar[6].block, Start: yyDollar[3].token.Context.Line, Context: yyDollar[7].token.Context}
			}
		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:232
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR && yyDollar[5].statement.NodeType() == NODE_ERROR {
				// 条件式のエラーを出力し、elseifs のエラーを返す
				err := yyDollar[2].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
				yyVAL.statement = yyDollar[5].statement.(*ParseError)
			} else if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else if yyDollar[5].statement == nil {
				yyVAL.statement = &IfStatement{Condition: yyDollar[2].expr, Consequence: yyDollar[4].block, Alternative: &BlockStatement{Block: []Statement{}}, Context: yyDollar[1].token.Context}
			} else if yyDollar[5].statement.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[5].statement.(*ParseError)
			} else if yyDollar[5].statement.NodeType() == NODE_BLOCK_STMT {
				yyVAL.statement = &IfStatement{Condition: yyDollar[2].expr, Consequence: yyDollar[4].block, Alternative: yyDollar[5].statement, Context: yyDollar[1].token.Context}
			} else {
				yyVAL.statement = &ParseError{Message: fmt.Sprintf(errcode.EINTERNAL, "IF"), Context: yyDollar[1].token.Context}
			}
		}
	case 21:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:251
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR && yyDollar[5].statement != nil && yyDollar[5].statement.NodeType() == NODE_ERROR {
				// 条件式のエラーを出力し、elseifs のエラーを返す
				err := yyDollar[2].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
				yyVAL.statement = yyDollar[5].statement
			} else if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else if yyDollar[5].statement == nil && yyDollar[7].block == nil {
				yyVAL.statement = &IfStatement{Condition: yyDollar[2].expr, Consequence: yyDollar[4].block, Alternative: &BlockStatement{Block: []Statement{}}, Context: yyDollar[1].token.Context}
			} else if yyDollar[5].statement == nil {
				yyVAL.statement = &IfStatement{Condition: yyDollar[2].expr, Consequence: yyDollar[4].block, Alternative: yyDollar[7].block, Context: yyDollar[1].token.Context}
			} else if yyDollar[5].statement.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[5].statement
			} else if block, ok := yyDollar[5].statement.(*BlockStatement); ok {
				if len(block.Block) != 1 || block.Block[0].NodeType() != NODE_IF_STMT {
					yyVAL.statement = &ParseError{Message: fmt.Sprintf(errcode.EINTERNAL, "IF-ELSE"), Context: yyDollar[1].token.Context}
				} else {
					last := getLastIfStatement(block.Block[0].(*IfStatement))
					if last.NodeType() == NODE_ERROR {
						yyVAL.statement = last.(*ParseError)
					} else {
						last.(*IfStatement).Alternative = yyDollar[7].block
						yyVAL.statement = &IfStatement{Condition: yyDollar[2].expr, Consequence: yyDollar[4].block, Alternative: yyDollar[5].statement, Context: yyDollar[1].token.Context}
					}
				}
			} else {
				yyVAL.statement = &ParseError{Message: fmt.Sprintf(errcode.EINTERNAL, "IF-ELSE"), Context: yyDollar[1].token.Context}
			}
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:282
		{
			yyVAL.statement = &FuncStatement{NameID: yyDollar[1].ident.NameID, Params: yyDollar[3].params, Block: yyDollar[5].block, Context: yyDollar[2].token.Context}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:286
		{
			if yyDollar[6].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[6].expr.(*ParseError)
			} else {
				yyVAL.statement = &FuncStatement{
					NameID:  yyDollar[2].ident.NameID,
					Params:  yyDollar[4].params,
					Block:   &BlockStatement{Block: []Statement{&ReturnStatement{Value: yyDollar[6].expr, Context: yyDollar[1].token.Context}}},
					Context: yyDollar[1].token.Context}
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:297
		{
			yyVAL.statement = &ReturnStatement{Value: nil, Context: yyDollar[1].token.Context}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:299
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				yyVAL.statement = &ReturnStatement{Value: yyDollar[2].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:307
		{
			yyVAL.statement = &MacroStatement{NameID: yyDollar[1].ident.NameID, Params: yyDollar[3].params, Body: yyDollar[5].block, End: yyDollar[6].token.Context.Line, Context: yyDollar[1].ident.Context}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:311
		{
			yyVAL.statement = &MacroCallStatement{NameID: yyDollar[1].token.SymbolID, Args: yyDollar[2].expr_list, Context: yyDollar[1].token.Context}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:315
		{
			yyVAL.statement = &MacroCallStatement{Label: yyDollar[1].expr, NameID: yyDollar[3].token.SymbolID, Args: yyDollar[4].expr_list, Context: yyDollar[3].token.Context}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:318
		{
			yyVAL.statement = &ExitmStatement{Context: yyDollar[1].token.Context}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:320
		{
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else {
				ctx := yyDollar[1].token.Context
				yyVAL.statement = &IfStatement{
					Condition:   yyDollar[3].expr,
					Consequence: &BlockStatement{Block: []Statement{&ExitmStatement{Context: ctx}}},
					Alternative: &BlockStatement{Block: []Statement{}},
					Context:     yyDollar[1].token.Context}
			}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:332
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:334
		{
			data := yyDollar[2].statement.(*DataDefineStatement)
			data.Label = yyDollar[1].expr
			yyVAL.statement = data
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:339
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:341
		{
			data := yyDollar[2].statement.(*DataStoreStatement)
			data.Label = yyDollar[1].expr
			yyVAL.statement = yyDollar[2].statement
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:346
		{
			yyVAL.statement = &OrgStatement{Address: yyDollar[2].expr, AllocType: ALLOC_ABS, Context: yyDollar[1].token.Context}
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:348
		{
			switch yyDollar[4].ident.NameID {
			case intern.Intern("ABS"):
				yyVAL.statement = &OrgStatement{Address: yyDollar[2].expr, AllocType: ALLOC_ABS, Context: yyDollar[1].token.Context}
			case intern.Intern("REL"):
				yyVAL.statement = &OrgStatement{Address: yyDollar[2].expr, AllocType: ALLOC_REL, Context: yyDollar[1].token.Context}
			default:
				yyVAL.statement = &ParseError{Message: errcode.EORG_ALLOC, Context: yyDollar[1].token.Context}
			}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:358
		{
			yyVAL.statement = &IncludeStatement{Filename: yyDollar[2].token.Literal, Context: yyDollar[1].token.Context}
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:360
		{
			yyVAL.statement = &CharmapStatement{NameID: yyDollar[2].token.SymbolID, Filename: yyDollar[4].expr, Context: yyDollar[1].token.Context}
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:364
		{
			yyVAL.statement = &CharmapStatement{NameID: yyDollar[2].token.SymbolID, Filename: yyDollar[4].expr, DefChar: yyDollar[6].expr, Context: yyDollar[1].token.Context}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:371
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				size := 0
				switch yyDollar[1].token.TokenSubType {
				case DB:
					size = 1
				case DW:
					size = 2
				case DD:
					size = 0
				}
				yyVAL.statement = &DataDefineStatement{Size: size, Values: []Expression{yyDollar[2].expr}, Context: yyDollar[1].token.Context}
			}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:388
		{
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else {
				s := yyDollar[1].statement.(*DataDefineStatement)
				s.Values = append(s.Values, yyDollar[3].expr)
				yyVAL.statement = s
			}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:400
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				var size int
				switch yyDollar[1].token.TokenSubType {
				case DSB:
					size = 1
				case DSW:
					size = 2
				}
				yyVAL.statement = &DataStoreStatement{Size: size, Count: yyDollar[2].expr, FillValue: nil, Context: yyDollar[1].token.Context}
			}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:415
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else if yyDollar[4].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else {
				size := 0
				switch yyDollar[1].token.TokenSubType {
				case DSB:
					size = 1
				case DSW:
					size = 2
				}
				yyVAL.statement = &DataStoreStatement{Size: size, Count: yyDollar[2].expr, FillValue: yyDollar[4].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:433
		{
			yyVAL.ident = &Ident{Name: yyDollar[1].token.Literal, NameID: yyDollar[1].token.SymbolID, IdentType: IDENT, Context: yyDollar[1].token.Context}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:434
		{
			yyVAL.ident = &Ident{Name: yyDollar[1].token.Literal, NameID: yyDollar[1].token.SymbolID, IdentType: LOCAL_IDENT, Context: yyDollar[1].token.Context}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:435
		{
			yyVAL.ident = &Ident{Name: yyDollar[1].token.Literal, NameID: yyDollar[1].token.SymbolID, IdentType: AT_IDENT, Context: yyDollar[1].token.Context}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:436
		{
			yyVAL.ident = &Ident{Name: yyDollar[1].token.Literal, NameID: yyDollar[1].token.SymbolID, IdentType: ANON_IDENT, Context: yyDollar[1].token.Context}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:439
		{
			yyVAL.expr = yyDollar[1].ident
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:441
		{
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.expr = yyDollar[3].expr.(*ParseError)
			} else {
				yyVAL.expr = buildInfixExpression(CONCAT, yyDollar[1].ident, yyDollar[3].expr, yyDollar[2].token.Context)
			}
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:450
		{
			yyVAL.params = []string{}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:451
		{
			yyVAL.params = []string{strings.ToUpper(yyDollar[1].token.Literal)}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:453
		{
			yyDollar[1].params = append(yyDollar[1].params, strings.ToUpper(yyDollar[3].token.Literal))
			yyVAL.params = yyDollar[1].params
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:459
		{
			yyVAL.statement = nil
		}
	case 54:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:461
		{
			ifst := &IfStatement{Condition: yyDollar[3].expr, Consequence: yyDollar[5].block, Alternative: &BlockStatement{Block: []Statement{}}, Context: yyDollar[2].token.Context}
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else if yyDollar[1].statement == nil {
				yyVAL.statement = &BlockStatement{Block: []Statement{ifst}}
			} else if block := yyDollar[1].statement.(*BlockStatement); len(block.Block) == 0 {
				block.Block = append(block.Block, ifst)
				yyVAL.statement = yyDollar[1].statement
			} else if len(block.Block) == 1 && block.Block[0].NodeType() == NODE_IF_STMT {
				stmt := block.Block[0].(*IfStatement)
				for {
					if stmt.Alternative == nil {
						stmt.Alternative = &BlockStatement{Block: []Statement{ifst}}
						yyVAL.statement = yyDollar[1].statement
						break
					} else if block := stmt.Alternative.(*BlockStatement); len(block.Block) == 0 {
						block.Block = append(block.Block, ifst)
						yyVAL.statement = yyDollar[1].statement
						break
					} else if len(block.Block) == 1 && block.Block[0].NodeType() == NODE_IF_STMT {
						stmt = block.Block[0].(*IfStatement)
						continue
					} else {
						yyVAL.statement = &ParseError{Message: fmt.Sprintf(errcode.EINTERNAL, "ELIF"), Context: yyDollar[2].token.Context}
						break
					}
				}
			}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:495
		{
			yyVAL.block = &BlockStatement{Block: []Statement{}}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:497
		{
			if yyDollar[2].statement == nil { // error
				// do nothing
			} else if yyDollar[2].statement.NodeType() == NODE_ERROR {
				err := yyDollar[2].statement.(*ParseError)
				yylex.Error(err.Message, err.Context)
			} else {
				yyDollar[1].block.Block = append(yyDollar[1].block.Block, yyDollar[2].statement.(Statement))
				yyVAL.block = yyDollar[1].block
			}
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:511
		{
			yyVAL.enum_elements = &EnumElements{Elements: []*EnumElement{}}
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:512
		{
			yyVAL.enum_elements = yyDollar[1].enum_elements
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:514
		{
			if yyDollar[2].statement.NodeType() == NODE_ERROR {
				err := yyDollar[2].statement.(*ParseError)
				yylex.Error(err.Message, err.Context)
			}
			yyDollar[1].enum_elements.Elements = append(yyDollar[1].enum_elements.Elements, yyDollar[2].statement.(*EnumElement))
			yyVAL.enum_elements = yyDollar[1].enum_elements
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:524
		{
			yyVAL.statement = &EnumElement{NameID: yyDollar[1].token.SymbolID, Value: nil, Context: yyDollar[1].token.Context}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:526
		{
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[3].expr.(*ParseError)
			} else {
				yyVAL.statement = &EnumElement{NameID: yyDollar[1].token.SymbolID, Value: yyDollar[3].expr, Context: yyDollar[1].token.Context}
			}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:536
		{
			yyVAL.statement = &Z80Instruction{InstType: Z80_INST0, Opcode: int(yyDollar[1].token.TokenSubType), Context: yyDollar[1].token.Context}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:540
		{
			yyVAL.statement = &Z80Instruction{InstType: Z80_INST1, Opcode: int(yyDollar[1].token.TokenSubType), Context: yyDollar[1].token.Context}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:544
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				yyVAL.statement = &Z80Instruction{InstType: Z80_INST1, Opcode: int(yyDollar[1].token.TokenSubType),
					Op1:     yyDollar[2].expr,
					Context: yyDollar[1].token.Context}
			}
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:554
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else {
				yyVAL.statement = &Z80Instruction{InstType: Z80_INST2, Opcode: int(yyDollar[1].token.TokenSubType),
					Op2:     yyDollar[2].expr,
					Context: yyDollar[1].token.Context}
			}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:564
		{
			if yyDollar[2].expr.NodeType() == NODE_ERROR && yyDollar[4].expr.NodeType() == NODE_ERROR {
				err := yyDollar[2].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else if yyDollar[2].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[2].expr.(*ParseError)
			} else if yyDollar[4].expr.NodeType() == NODE_ERROR {
				yyVAL.statement = yyDollar[4].expr.(*ParseError)
			} else {
				yyVAL.statement = &Z80Instruction{InstType: Z80_INST2, Opcode: int(yyDollar[1].token.TokenSubType),
					Op1:     yyDollar[2].expr,
					Op2:     yyDollar[4].expr,
					Context: yyDollar[1].token.Context}
			}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:584
		{
			reg := &RegisterLiteral{RegisterType: int(yyDollar[2].token.TokenType), Register: int(yyDollar[2].token.TokenSubType), Context: yyDollar[2].token.Context}
			yyVAL.expr = &RegIndirectExpression{
				Register: reg,
				Context:  yyDollar[1].token.Context}
		}
	case 68:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:591
		{
			reg := &RegisterLiteral{RegisterType: int(yyDollar[2].token.TokenType), Register: int(yyDollar[2].token.TokenSubType), Context: yyDollar[2].token.Context}
			yyVAL.expr = &RegIndirectExpression{
				Register:     reg,
				Displacement: buildPrefixExpression(int(yyDollar[3].token.TokenSubType), yyDollar[4].expr, yyDollar[1].token.Context),
				Context:      yyDollar[1].token.Context}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:599
		{
			reg := &RegisterLiteral{RegisterType: int(yyDollar[2].token.TokenType), Register: int(yyDollar[2].token.TokenSubType), Context: yyDollar[2].token.Context}
			yyVAL.expr = &RegIndirectExpression{
				Register: reg,
				Context:  yyDollar[1].token.Context}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:606
		{
			yyVAL.expr = &AddrIndirectExpression{Address: yyDollar[2].expr, Context: yyDollar[1].token.Context}
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:609
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:614
		{
			yyVAL.expr_list = &ExpressionList{Expressions: []Expression{}}
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:616
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				err := yyDollar[1].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
			}
			yyVAL.expr_list = &ExpressionList{Expressions: []Expression{yyDollar[1].expr}}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:624
		{
			if yyDollar[3].expr.NodeType() == NODE_ERROR {
				err := yyDollar[3].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
			}
			yyDollar[1].expr_list.Expressions = append(yyDollar[1].expr_list.Expressions, yyDollar[3].expr)
			yyVAL.expr_list = yyDollar[1].expr_list
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:634
		{
			yyVAL.token = yyDollar[1].token
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:636
		{
			tok := yyVAL.token
			tok.Literal += yyDollar[2].token.Literal
			yyVAL.token = tok
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:644
		{
			n, err := parseInt(yyDollar[1].token.Literal)
			if err == nil {
				yyVAL.expr = &NumberLiteral{Value: int(n), Context: yyDollar[1].token.Context}
			} else {
				yyVAL.expr = &ParseError{Message: fmt.Sprintf(errcode.ENUMBER_LITERAL, yyDollar[1].token.Literal), Context: yyDollar[1].token.Context}
			}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:652
		{
			yyVAL.expr = &StringLiteral{Value: yyDollar[1].token.Literal, Context: yyDollar[1].token.Context}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:653
		{
			yyVAL.expr = &RegisterLiteral{RegisterType: int(yyDollar[1].token.TokenType), Register: int(yyDollar[1].token.TokenSubType), Context: yyDollar[1].token.Context}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:654
		{
			yyVAL.expr = &RegisterLiteral{RegisterType: int(yyDollar[1].token.TokenType), Register: int(yyDollar[1].token.TokenSubType), Context: yyDollar[1].token.Context}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:655
		{
			yyVAL.expr = &FlagLiteral{Flag: int(yyDollar[1].token.TokenSubType), Context: yyDollar[1].token.Context}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:656
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:658
		{
			name := strings.ToUpper(yyDollar[1].token.Literal)
			names := strings.Split(name, ".")
			yyVAL.expr = &DotIdent{Name: name, NameID: yyDollar[1].token.SymbolID, Left: intern.Intern(names[0]), Right: intern.Intern("." + names[1]), Context: yyDollar[1].token.Context}
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:663
		{
			yyVAL.expr = &FuncCallExpression{Name: strings.ToUpper(yyDollar[1].token.Literal), NameID: yyDollar[1].token.SymbolID, Args: yyDollar[3].expr_list, Context: yyDollar[1].token.Context}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:664
		{
			yyVAL.expr = &ArrayLiteral{Elements: yyDollar[2].expr_list, Context: yyDollar[1].token.Context}
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:665
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:666
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:667
		{
			yyVAL.expr = buildInfixExpression(int(yyDollar[2].token.TokenSubType), yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:668
		{
			yyVAL.expr = buildInfixExpression(int(yyDollar[2].token.TokenSubType), yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:669
		{
			yyVAL.expr = buildInfixExpression(int(yyDollar[2].token.TokenSubType), yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:670
		{
			yyVAL.expr = buildInfixExpression(int(yyDollar[2].token.TokenSubType), yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:671
		{
			yyVAL.expr = buildInfixExpression(OR, yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:672
		{
			yyVAL.expr = buildInfixExpression(AND, yyDollar[1].expr, yyDollar[3].expr, yyDollar[2].token.Context)
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:673
		{
			yyVAL.expr = buildPrefixExpression(int(yyDollar[1].token.TokenSubType), yyDollar[2].expr, yyDollar[1].token.Context)
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:674
		{
			yyVAL.expr = buildPrefixExpression(int(yyDollar[1].token.TokenSubType), yyDollar[2].expr, yyDollar[1].token.Context)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:678
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR {
				err := yyDollar[1].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)
				yylex.Error(errcode.EARRAY_NAME, yyDollar[2].token.Context)
			}
			yyVAL.expr = &ParseError{Message: errcode.EARRAY_INDEX, Context: yyDollar[2].token.Context}
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:687
		{
			if yyDollar[1].expr.NodeType() == NODE_ERROR && yyDollar[3].expr.NodeType() == NODE_ERROR {
				yylex.Error(errcode.EARRAY_NAME, yyDollar[2].token.Context)
				err := yyDollar[1].expr.(*ParseError)
				yylex.Error(err.Message, err.Context)

				yylex.Error(errcode.EARRAY_INDEX, yyDollar[2].token.Context)
				yyVAL.expr = yyDollar[3].expr
			} else if yyDollar[1].expr.NodeType() == NODE_ERROR {
				yylex.Error(errcode.EARRAY_NAME, yyDollar[2].token.Context)
				yyVAL.expr = yyDollar[1].expr
			} else if yyDollar[3].expr.NodeType() == NODE_ERROR {
				yylex.Error(errcode.EARRAY_INDEX, yyDollar[2].token.Context)
				yyVAL.expr = yyDollar[3].expr
			} else {
				yyVAL.expr = &IndexedExpression{Left: yyDollar[1].expr, Index: yyDollar[3].expr, Context: yyDollar[2].token.Context}
			}
		}
	}
	goto yystack /* stack new state and value */
}
