package parser

var grammerRules map[int]string = map[int]string{
	1:  "program: .",
	2:  "program:  program EOL.",
	5:  "program:  program statement.",
	51: "expr:  IDENT.",
	35: "label:  LOCAL_IDENT.",
	49: "expr:  NUMBER.",
	50: "expr:  STRING.",
	52: "expr:  DOT_IDENT.",
	46: "expr_list: .",
	55: "expr:  indexed_expr.",
	56: "expr:  Z80_REG8.",
	57: "expr:  Z80_REG16.",
	58: "expr:  Z80_FLAG.",
	36: "instruction:  Z80_INST0.",
	37: "instruction:  Z80_INST1.",
	3:  "program:  program label EOL.",
	4:  "program:  program label statement.",
	20: "param_list: .",
	33: "label:  IDENT ':'.",
	34: "label:  LOCAL_IDENT ':'.",
	6:  "statement:  expr EOL.",
	7:  "statement:  instruction EOL.",
	8:  "statement:  directive EOL.",
	9:  "statement:  error EOL.",
	47: "expr_list:  expr.",
	67: "expr:  '-' expr.",
	68: "expr:  UNARY expr.",
	39: "instruction:  Z80_INST1 expr.",
	41: "instruction:  Z80_INST2 expr.",
	11: "directive:  IDENT EQU expr.",
	28: "enum_elements: .",
	21: "param_list:  IDENT.",
	14: "directive:  expr '=' expr.",
	60: "expr:  expr ADDSUB expr.",
	61: "expr:  expr '-' expr.",
	62: "expr:  expr MULDIV expr.",
	63: "expr:  expr COMP expr.",
	64: "expr:  expr SHIFT expr.",
	65: "expr:  expr OR expr.",
	66: "expr:  expr AND expr.",
	69: "indexed_expr:  expr '[' ']'.",
	54: "expr:  '[' expr_list ']'.",
	15: "directive:  indexed_expr '=' expr.",
	59: "expr:  '(' expr ')'.",
	25: "block_statement: .",
	53: "expr:  expr '(' expr_list ')'.",
	70: "indexed_expr:  expr '[' expr ']'.",
	48: "expr_list:  expr_list ',' expr.",
	38: "instruction:  Z80_INST1 '(' expr ')'.",
	40: "instruction:  Z80_INST2 '(' expr ')'.",
	45: "instruction:  Z80_INST2 expr ',' expr.",
	10: "directive:  CONST IDENT '=' expr.",
	13: "directive:  VAR IDENT '=' expr.",
	23: "elseifs: .",
	12: "directive:  IDENT ENUM EOL enum_elements ENDE.",
	29: "enum_elements:  enum_elements EOL.",
	31: "enum_element:  IDENT.",
	22: "param_list:  param_list ',' IDENT.",
	16: "directive:  REPEAT expr EOL block_statement ENDR.",
	26: "block_statement:  block_statement EOL.",
	27: "block_statement:  block_statement statement.",
	30: "enum_elements:  enum_elements enum_element EOL.",
	19: "directive:  IDENT FUNC param_list EOL block_statement ENDF.",
	42: "instruction:  Z80_INST2 '(' expr ')' ',' expr.",
	43: "instruction:  Z80_INST2 expr ',' '(' expr ')'.",
	17: "directive:  IF expr EOL block_statement elseifs ENDIF.",
	32: "enum_element:  IDENT '=' expr.",
	44: "instruction:  Z80_INST2 '(' expr ')' ',' '(' expr ')'.",
	18: "directive:  IF expr EOL block_statement elseifs ELSE block_statement ENDIF.",
	24: "elseifs:  elseifs ELIF expr EOL block_statement.",
}
