package parser

var grammerRules map[int]string = map[int]string{
	1:  "program: .",
	2:  "program:  program statement.",
	3:  "statement:  EOL.",
	4:  "statement:  label EOL.",
	5:  "statement:  label instruction EOL.",
	6:  "statement:  instruction EOL.",
	7:  "statement:  directive EOL.",
	8:  "statement:  expr EOL.",
	9:  "statement:  error EOL.",
	10: "directive:  CONST ident '=' expr.",
	11: "directive:  ident EQU expr.",
	12: "directive:  ident ENUM EOL enum_elements ENDE.",
	13: "directive:  VAR ident '=' expr.",
	14: "directive:  expr '=' expr.",
	15: "directive:  REPT expr EOL block_statement ENDR.",
	16: "directive:  IF expr EOL block_statement elseifs ENDIF.",
	17: "directive:  IF expr EOL block_statement elseifs ELSE block_statement ENDIF.",
	18: "directive:  ident FUNC param_list EOL block_statement ENDF.",
	19: "directive:  FUNCTION ident '(' param_list ')' expr.",
	20: "directive:  EXITM.",
	21: "directive:  RETURN.",
	22: "directive:  RETURN expr.",
	23: "directive:  ident PROC.",
	24: "directive:  ENDP.",
	25: "directive:  IDENT MACRO param_list EOL block_statement ENDM.",
	26: "directive:  IDENT expr_list.",
	27: "ident:  IDENT.",
	28: "ident:  LOCAL_IDENT.",
	29: "param_list: .",
	30: "param_list:  IDENT.",
	31: "param_list:  param_list ',' IDENT.",
	32: "elseifs: .",
	33: "elseifs:  elseifs ELIF expr EOL block_statement.",
	34: "block_statement: .",
	35: "block_statement:  block_statement statement.",
	36: "enum_elements: .",
	37: "enum_elements:  enum_elements EOL.",
	38: "enum_elements:  enum_elements enum_element EOL.",
	39: "enum_element:  IDENT.",
	40: "enum_element:  IDENT '=' expr.",
	41: "label:  IDENT ':'.",
	42: "label:  LOCAL_IDENT ':'.",
	43: "label:  LOCAL_IDENT.",
	44: "instruction:  Z80_INST0.",
	45: "instruction:  Z80_INST1.",
	46: "instruction:  Z80_INST1 operand.",
	47: "instruction:  Z80_INST2 operand.",
	48: "instruction:  Z80_INST2 operand ',' operand.",
	49: "operand:  '(' Z80_REG16 ')'.",
	50: "operand:  '(' Z80_REG16 ADDSUB expr ')'.",
	51: "operand:  '(' Z80_REG8 ')'.",
	52: "operand:  '(' expr ')'.",
	53: "operand:  expr.",
	54: "expr_list:  expr.",
	55: "expr_list:  expr_list ',' expr.",
	56: "expr:  NUMBER.",
	57: "expr:  STRING.",
	58: "expr:  Z80_REG8.",
	59: "expr:  Z80_REG16.",
	60: "expr:  Z80_FLAG.",
	61: "expr:  IDENT.",
	62: "expr:  LOCAL_IDENT.",
	63: "expr:  DOT_IDENT.",
	64: "expr:  IDENT '(' ')'.",
	65: "expr:  IDENT '(' expr_list ')'.",
	66: "expr:  '[' ']'.",
	67: "expr:  '[' expr_list ']'.",
	68: "expr:  indexed_expr.",
	69: "expr:  '(' expr ')'.",
	70: "expr:  expr ADDSUB expr.",
	71: "expr:  expr MULDIV expr.",
	72: "expr:  expr COMP expr.",
	73: "expr:  expr SHIFT expr.",
	74: "expr:  expr OR expr.",
	75: "expr:  expr AND expr.",
	76: "expr:  ADDSUB expr.",
	77: "expr:  UNARY expr.",
	78: "indexed_expr:  expr '[' ']'.",
	79: "indexed_expr:  expr '[' expr ']'.",
}
